### ISSUE TITLE
Upload/Download to Host Function

### ISSUE THREAD

**Issue by hobonos** [DFRobot/DFRobot_ID809_I2C#1]
While there are commands for uploading and downloading to/from host(CMD_UP_CHAR, CMD_DOWN_CHAR) there is no functions that I can use. I am trying to upload/download the template generated by the device. Can you guys help me with that?

Also if you can; can you upload the English version of the ID1016c datasheet?

**Comment by pleasetakeup** [comment]
sorry ，We do not have an English version of the data sheet

**Comment by pleasetakeup** [comment]
About the fingerprint template to upload and download, please refer to https://github.com/DFRobot/DFRobot_ID809

the library of DFRobot_ID809_I2C uses I2C communication, but actually the fingerprint module communicates with Uart and then converts to I2C data via the transfer board

However, the communication rate of I2C is not high enough, so there is no API for uploading and downloading templates in DFRobot_ID809_I2C

DFRobot_ID809 uses UART to drive the fingerprint module directly. There are apis and code about template in this library 

![WN0{$@L(}7CB5P4 DXY%ISR](https://user-images.githubusercontent.com/49088278/158962585-505b22c4-478d-446e-b18b-668ea412f5a5.png)

It's actually possible to upload and download template data using I2C, but performance is not good
If you need to use I2C communication in your project, you can move the function to get the template from DFRobot_ID809 to DFRobot_ID809_I2C, which should be able to use directly. Ask me if you make a mistake

**Comment by hobonos** [comment]
Thank you for the reply, I've decided to go with UART communication. 
Have a wonderful day.
