### ISSUE TITLE
I2C Pins to use for interfacing with ESP32S3

### ISSUE THREAD

**Issue by sumit809** [DFRobot/DFRobot_ID809_I2C#2]
Hi,

I'm trying to figure out the SDA and SCL pins of ESP32S3 for interfacing SEN0359 gravity board (UART to I2C breakout)
I don't know the pins and I'm not also able to pass the software SDA-SCL pins as arguments in .begin() function.
Is there a way-out?

Thanks in Advance!

**Comment by qsjhyy** [comment]
![image](https://github.com/DFRobot/DFRobot_ID809_I2C/assets/78136558/e8257a9d-84ee-40aa-a5cb-c6ea6ef85080)
Are you unsure about the default I2C pins of ESP32S3? Perhaps you can find a file in your Arduino IDE's SDK that will tell you the default I2C pin numbers for ESP32S3. Hopefully, this can help you resolve your issue.

**Comment by qsjhyy** [comment]
No reply for too long, so temporarily closed

**Comment by dylanwe** [comment]
I've checked the default pins on my esp32 it's 21 for SDA and 22 for SCL. The code from the example still isn't able to make a connection.

**Comment by qsjhyy** [comment]
I did not find this problem when I tested it. Could you please use the latest updated version library for testing feedback? Thank you.You can scan the i2c address, that may indeed be a problem with the library, but I did not test found.

**Comment by dylanwe** [comment]
I was able to find the I2C address

**Comment by qsjhyy** [comment]
okay, this place can be closed for now
