### ISSUE TITLE
Store fingerprint data into a external database

### ISSUE THREAD

**Issue by pepijndik** [DFRobot/DFRobot_ID809_I2C#7]
In the non ic2 I saw a method get full image, how do you recommend to store the registered fingerprints in an external DB?

**Comment by pepijndik** [comment]
Also a strange thing is that when I use the 1.1.1 version, my wemos d1 mini can't communicate anymore while the 1.1.0 works (didn't  change any writing)

**Comment by qsjhyy** [comment]
https://github.com/DFRobot/DFRobot_ID809_I2C/issues/5#issuecomment-1993763632 Maybe you have the same problem, and you can test it to see if this is the case.

**Comment by pepijndik** [comment]
> https://github.com/DFRobot/DFRobot_ID809_I2C/issues/5#issuecomment-1993763632 Maybe you have the same problem, and you can test it to see if this is the case.

I think this indeed the same issue, do you have any recommendations to store the scanned fingerprints into a external DB? 
I tought to retrieve the fullimage or just the bytes of the fingerprint. 

But i cant find any information or code refrences in this repo. To accomolish my need

**Comment by qsjhyy** [comment]
![image](https://github.com/DFRobot/DFRobot_ID809_I2C/assets/78136558/c5c91b48-af87-465c-ae4d-136fdf4fdbd4)
As this API shows, image data is stored directly inside the module, and the i2c interface is not a good way to transfer images and process them quickly.
![image](https://github.com/DFRobot/DFRobot_ID809_I2C/assets/78136558/d3c8b2cf-9cdd-452a-becf-13385a64ce44)
![image](https://github.com/DFRobot/DFRobot_ID809_I2C/assets/78136558/bce83354-9894-40a5-8b31-179c519f3615)
That's really all this simple module does.

**Comment by pepijndik** [comment]
> ![image](https://github.com/DFRobot/DFRobot_ID809_I2C/assets/78136558/c5c91b48-af87-465c-ae4d-136fdf4fdbd4)
> As this API shows, image data is stored directly inside the module, and the i2c interface is not a good way to transfer images and process them quickly.
> ![image](https://github.com/DFRobot/DFRobot_ID809_I2C/assets/78136558/d3c8b2cf-9cdd-452a-becf-13385a64ce44)
> ![image](https://github.com/DFRobot/DFRobot_ID809_I2C/assets/78136558/bce83354-9894-40a5-8b31-179c519f3615)
> That's really all this simple module does.

Oke, mm thanks for your reply then i need to extend this repo. I understand that ic2 isnt the best way to transfare images but because my application requires a external  database  i need to think in solutions 🤔😃. (I am working on a school project where we are designing iot devices. And my project is a attendance registration device) and because there can be multiple devices in a building i need to store the fingerprint data/image in a db to check if they are enrolled and have access.

**Comment by qsjhyy** [comment]
https://wiki.dfrobot.com/Capacitive_Fingerprint_Sensor_SKU_SEN0348
https://wiki.dfrobot.com/SKU_SEN0542_Capacitive_Fingerprint_Sensor_UART_FPC_Connector
![image](https://github.com/DFRobot/DFRobot_ID809_I2C/assets/78136558/af26f24d-f356-4fd8-bb1b-d58e9c9244b7)

You can check out the two uart fingerprint recognition wikis, this one may be useful for you. However, you still need to test and evaluate, because if there are many fingerprints, the comparison time may be slow.

**Comment by pepijndik** [comment]
> https://wiki.dfrobot.com/Capacitive_Fingerprint_Sensor_SKU_SEN0348 https://wiki.dfrobot.com/SKU_SEN0542_Capacitive_Fingerprint_Sensor_UART_FPC_Connector ![image](https://private-user-images.githubusercontent.com/78136558/313527948-af26f24d-f356-4fd8-bb1b-d58e9c9244b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NjY3NTksIm5iZiI6MTcxMDc2NjQ1OSwicGF0aCI6Ii83ODEzNjU1OC8zMTM1Mjc5NDgtYWYyNmYyNGQtZjM1Ni00ZmQ4LWJiMWItZDU4ZTljOTI0NGI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDEyNTQxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0NmQyYTUwNmFiMGM3MDlmOGU4YWFkY2VmYWYxNjEyOWVlYWRiNjhmZDY5YWQwOGEwOWZjM2M1ZjgxYWFmYjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KAYET661sALMv26g7-q4kzPclDfYdVjyWIwFhqD95ro)
> 
> You can check out the two uart fingerprint recognition wikis, this one may be useful for you. However, you still need to test and evaluate, because if there are many fingerprints, the comparison time may be slow.

Thanks, then I will check this out.  when I came up with something I will share it ;-)

**Comment by qsjhyy** [comment]
well, good luck.
